name = input("What's your name? ")
age = input("Enter your age: ")
major = input("What's your major? ")
semester = input("In which semester you're currently enrolled? ")
print("=====Student's Info=====")
print("Name:",name)
print("Age:",age)
print("Major:",major)
print("Semester:",semester)